version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  pgadmin4:
    image: dpage/pgadmin4:5.6
    container_name: pgadmin4
    ports:
      - 80:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pdadmin4@email.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
    hostname: pgadmin4
    depends_on:
      - db
    restart: always

  backend:
    tty: true
    build:
      context: ./portfolio-backend/
      dockerfile: Dockerfile
    volumes:
      - ./portfolio-backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  frontend:
    build:
      context: ./portfolio-frontend/
      dockerfile: Dockerfile
    volumes:
      - ./portfolio-frontend/app:/usr/src/app
    command: 'yarn dev'
    ports:
      - '8000:3000'

volumes:
  postgres-db:
    driver: local
  pgadmin:
    driver: local