version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  # pgadmin4:
  #   image: dpage/pgadmin4:5.6
  #   container_name: pgadmin4
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./pgadmin:/var/lib/pgadmin/storage
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: postgres
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   hostname: pgadmin4
  #   restart: always

  backend:
    tty: true
    build:
      context: ./portfolio-backend/
      dockerfile: Dockerfile
    volumes:
      - ./portfolio-backend:/app
    command: rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./portfolio-frontend/
      dockerfile: Dockerfile
    volumes:
      - ./portfolio-frontend/app:/usr/src/app
    command: 'yarn dev'
    ports:
      - '8000:3000'